# This workflow only run if Lint and Test workflow has passed.
# For more information see: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_run

name: Publish npm package

on:
  workflow_run:
    workflows: ["Lint and Test"]
    types: [completed]
    tags: ['*']

jobs:
  publish_npm:
    name: 'Publish npm package'
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          cache: npm
          tag_name: 'v%s'
          registry-url: 'https://registry.npmjs.org'
          scope: '@geolonia'
      - run: npm install
      - run: npm run build
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
